apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polkadot-app
  name: polkadot-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: polkadot-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: polkadot-app
    spec:
      containers:
      - image: parity/polkadot:v0.9.12
        imagePullPolicy: Always
        name: polkadot
        args: ["--name", "arminTeimouriNode", "--chain", "westend", "--prometheus-port", "9615", "--port", "30333","--telemetry-url", "https://telemetry.polkadot.io 1"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "2"
        volumeMounts:
        - mountPath: /data
          name: test-volume
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
      - name: test-volume
        emptyDir: {}
