replicaCount: 1

image:
  repository: "parity/polkadot"
  pullPolicy: Always
  tag: "v0.9.12"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false


polkaNode:
  name: "arminTeimouriNode"
  serviceMonitor: 
    enabled: true
  chain: "westend"
  port: "30333"
  args:
    - "--prometheus-external"
    - "--rpc-external"
    - "--ws-external"
    - "--rpc-cors=all"
    - "--telemetry-url"
    - "https://telemetry.polkadot.io 1"

 
securityContext:
  runAsNonRoot: true


service:
  type: ClusterIP
  headlessServce: 
    enabled: true
  port: 9944

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: arminteimouri-westend-node.teymuri.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: "2"
    memory: "2048Mi"
    ephemeral-storage: "500M"
  requests:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: "256M"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


storageClaim:
  class: "default"
  volumeSize: 10Gi

nodeSelector: {}

tolerations: []

affinity: {}

terminationGracePeriodSeconds: 60