{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/NetworkPolicy" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: polka-network
  namespace: {{ $.Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "polkadot.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
#  - Egress
  ingress:
  - from:
    ports:
      - port: 9615
        protocol: TCP
      - port: 30333
        protocol: TCP
      - port: 9944
        protocol: TCP
      - port: 9933
        protocol: TCP
#  egress:
#  - to:
#    ports:
#    - protocol: TCP
#      port: 443
#    - protocol: TCP
#      port: 30333
{{- end }}