apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkadot.fullname" . }}
  labels:
    {{- include "polkadot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if $.Values.service.headlessServce.enabled }}
  clusterIP: None
  {{- end }}
  ports:
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
    - port: 9615
      name: prometheus
  selector:
    {{- include "polkadot.selectorLabels" . | nindent 4 }}
